//独立COOKIE文件     ck在``里面填写，多账号换行

let yuedongzutokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wveXVlZG9uZ3p1LnlpY2hlbmd3LmNuXC9hcHBzXC9sb2dpblwvd2VjaGF0IiwiaWF0IjoxNjE0NjUwMzAyLCJleHAiOjIwNTM2MjUwMzAyLCJuYmYiOjE2MTQ2NTAzMDIsImp0aSI6IlZ6QkRGYlRUTW84Q0FESk8iLCJzdWIiOjMxNDg5LCJwcnYiOiI0MWRmODgzNGYxYjk4ZjcwZWZhNjBhYWVkZWY0MjM0MTM3MDA2OTBjIn0.ADeYftNcQyJFCy8dzDknBKs33mhoaTTak-DGbnYQjxI`



let yuedongzucookie = {
    yuedongzutokenVal: yuedongzutokenVal,

}

module.exports = yuedongzucookie
